name: Deploy Node.js QR API

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update files and restart API
        run: |
          # 1. Синхронизируем новые файлы из GitHub в рабочую папку на ВМ
          # Исключаем node_modules, чтобы Docker сам их устанавливал внутри
          rsync -avz --delete --exclude 'node_modules' --exclude '.git' ./ /opt/sites/qr-api/
          
          # 2. Переходим в папку проекта
          cd /opt/sites/qr-api
          
          # 3. Запускаем/Перезапускаем контейнер. 
          # При рестарте он сам сделает npm install для новых пакетов и подхватит свежий index.js
          docker compose up -d --build
          docker compose restart
